---
title: "母校の中学3年生を東大工学部にご招待しました！"
author: "Haruto Ito"
date: "2026-09-18"
lang: ja
categories: [日本語]
---

昨日，母校（兵庫県立大学附属中学校）の中学3年生が修学旅行で東京大学に来られるとのことで，
私の学科である社会基盤学科がメインで使っている工学部1号館にお迎えし，「中学で学んだことと研究」というテーマにて少しお話をさせていただきました（[中学校の記事](https://dmzcms.hyogo-c.ed.jp/kendai-hs/NC3/blogs/blog_entries/view/117/67494ac757f878f585d6df1ef47a5942)）．

## 「好きなこと」と専門分野が接続していなかった頃

私自身，道路や鉄道，また広く地理や社会に幼少期から関心が強く，
一度通れば道は覚える，地図をひたすら眺める，都道府県や主要都市の人口は覚えているというような少年だったのですが，
そもそもこのような，「ただただ好きなこと」と，大学の専門分野や仕事というのが**一切接続しておらず**，
能力的には理系だという自覚があったので，なんとなく「機械とかをやるのかな」と思っていたし，
そういうエンジニアのような比較的想像しやすい仕事しか知らなかったので，
まさか大学で社会基盤という分野に出会うとは想像もつかなかったわけです．

そして，いざその「本当に好きな分野」にたどり着いた時には，今まで学校や趣味でやってきた，人生における多くの**点と点がどんどん結びついていく**．
道路と鉄道について詳しいし，色々考えてきたというのは，研究における社会課題の発見とテーマ設定になくてはならないことだと思っています．
そして，それ以外でも数学も英語もプレゼンも（最近はAI任せですが）プログラミングも，
どれも独立に学校なり自主的になりでやってきたことですが，気づいたらそれら全部が今の自分の研究につながっているんですね．

高校一年生の担任の先生に度々言われたことをよく覚えています．

> 「大人になったら今やっていることの点と点がつながって線になる瞬間があるんだよ．」
>
> — 高校一年生の担任の先生

その時はこの言葉の意味は正直想像がついていなかったし，これを理解するっていうのは中学生や高校生にはかなり難しい気がしています．
今でこそ，その意味を身に染みて感じているものの，
この言葉の意味を理解しないまま，成績という外的動機づけによって必死に勉強をしないといけないというのは，中高生にとって大変苦しいことだろうと思うわけです[^motivation]．
仮に完全にはわからなくても，少しでも想像がついて信じて内発的な動機で学習を進めてくれたらいいなと．

[^motivation]: 今となっては当時の自分がどういう気持ちや動機づけで勉強をしていたのかは思い出せない...

## 中学校で習った知識を，自分が使っていた

そして何より懐かしい先生方に会えたことがとても嬉しかったです．
今回ご連絡をいただいたのが，私の頃からの社会の先生でして，
そういえば先生に[ウェーバーの工業立地論](https://ja.wikipedia.org/wiki/工業立地論)
というのを習ったなあというのを思い出しました．
中学校で習った「何の役に立つの？」みたいな知識を，ここにきて自分自身が使っていたことに今更ながら気づきました．
これって基本的には同じ考え方じゃないかと[^weber]．

[^weber]: もちろん厳密には，ウェーバーの工業立地論をそのまま空間経済学に適用して説明するには無理があるところもあるわけですが．

この感動は伝えなきゃ，と思って今回の15分ほどのプレゼンを組み立てたわけですが，
個人的には（僕自身と同じように主要都市の人口を覚えている子がいたり，鉄道好きの子がたくさんいるというのも相まってか）結構手応えのある回になったと感じています．
後輩が僕よりも早くに関心のあることと社会との接続を見つけてくれること，
そして仮にすぐには見つからなかったとしても，今の勉強とかが将来線になって自分の好きに繋がるかもしれないと信じて今を頑張ってくれることを願っています．