project:
  type: website
  output-dir: ../docs/ja

website:
  title: "伊藤 晴人"
  navbar:
    left:
      - text: "Projects"
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/ito-haru
      - icon: linkedin
        href: https://www.linkedin.com/in/haruto-ito/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    include-in-header:
      - ../google-site-verification.html
